### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by infomaniac50** [vdsabev/image-downloader#23]
I got this exception on http://www.b2cjewels.com/. The problem goes away if I uncheck "Show image width filter" and "Show image height filter"

```
Uncaught DOMException: Failed to execute 'webkitMatchesSelector' on 'Element': 'img[src="http://www.b2cjewels.com/B2CTheme/images/arrow-dropdown.png"), url("/B2CTheme/images/pt-metal-fliter.png"]' is not a valid selector.
    at O.matches (chrome-extension://cnpniohnfphhjihaiiggeabnkjhpaldj/lib/zepto.js:2:2913)
    at chrome-extension://cnpniohnfphhjihaiiggeabnkjhpaldj/lib/zepto.js:2:23625
    at a (chrome-extension://cnpniohnfphhjihaiiggeabnkjhpaldj/lib/zepto.js:2:22611)
    at Object.e.matches (chrome-extension://cnpniohnfphhjihaiiggeabnkjhpaldj/lib/zepto.js:2:23593)
    at chrome-extension://cnpniohnfphhjihaiiggeabnkjhpaldj/lib/zepto.js:2:6142
    at Array.filter (<anonymous>)
    at Array.filter (chrome-extension://cnpniohnfphhjihaiiggeabnkjhpaldj/lib/zepto.js:2:6111)
    at X (chrome-extension://cnpniohnfphhjihaiiggeabnkjhpaldj/lib/zepto.js:2:1281)
    at Array.children (chrome-extension://cnpniohnfphhjihaiiggeabnkjhpaldj/lib/zepto.js:2:7429)
    at chrome-extension://cnpniohnfphhjihaiiggeabnkjhpaldj/scripts/popup.js:299:36
```

**Comment by vdsabev** [comment]
Thanks so much for the report! Hopefully it's fixed in 2.4.1. If your extension doesn't update automatically, you can force an update if you open `chrome://extensions/`

Let me know how it works out!
